# Generated by Django 3.1.2 on 2021-01-26 16:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrolladora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, verbose_name='Desarrolladora')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Género')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('idJuego', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url_imagen', models.URLField()),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('puntuacion_critica', models.PositiveSmallIntegerField()),
                ('fecha', models.DateField(verbose_name='Fecha de salida')),
                ('desarrolladora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.desarrolladora')),
                ('generos', models.ManyToManyField(to='main.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, verbose_name='Plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('idValoracion', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('usuario', models.CharField(max_length=100)),
                ('sitio', models.CharField(max_length=100)),
                ('puntuacion', models.IntegerField(verbose_name=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]))),
                ('texto', models.TextField()),
                ('mi_valoracion', models.BooleanField()),
                ('juego', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.juego')),
            ],
        ),
    ]
